
### def :
Association Rule Learning is a machine learning technique used to discover interesting relationships or patterns between items in large datasets.

It is mainly used in:

Market basket analysis
Recommendation systems
Customer behavior analysis
Simple Idea

Association Rule Learning answers questions like:

“If a customer buys item A, what other item is likely to be bought?”

Example:

Customers buying bread often buy butter.

So the rule becomes:

Bread → Butter
Real-Life Example

In supermarkets:

Milk → Bread

means:

Customers who buy milk are also likely to buy bread.

This helps stores:

arrange products
create offers
improve sales
Working of Association Rule Learning
Step 1: Collect Transaction Data

Example dataset:

Transaction ID	Items Purchased
T1	Bread, Butter, Milk
T2	Bread, Jam
T3	Milk, Butter
T4	Bread, Butter

Step 2: Find Frequent Itemsets
The algorithm identifies item combinations that occur frequently.
Example:

Bread & Butter
Milk & Butter

Step 3: Generate Association Rules

Rules are formed like:
Bread → Butter

Meaning:

If Bread is purchased,
Butter is likely purchased too.

Important Terms
1. Support
Support measures how frequently an itemset appears.

Formula:
Support(A→B)=Transactions containing A and B / Total Transactions
Higher support means:rule appears more often.


2. Confidence

Confidence measures how often B is purchased when A is purchased.

Formula:

Confidence(A→B)=
Transactions containing A
Transactions containing A and B
	​


Higher confidence means:

stronger relationship.
3. Lift

Lift measures how strongly two items are related.

Formula:

Lift(A→B)=
Support(B)
Confidence(A→B)
	​


Interpretation:

Lift > 1 → positive association
Lift = 1 → no association
Lift < 1 → negative association
Types of Association Rule Algorithms
1. Apriori Algorithm

Most popular algorithm.

Working:

Finds frequent itemsets
Generates rules step by step
2. Eclat Algorithm

Uses depth-first search for faster processing.

3. FP-Growth Algorithm

Efficient for large datasets.

Example of Apriori Rule

Suppose:

80% of customers buying bread also buy butter

Rule:

Bread → Butter

Confidence = 80%

## Applications

Association Rule Learning is used in:

Market basket analysis
Product recommendation
Cross-selling
Website recommendation
Medical diagnosis
Fraud detection
## Advantages
Finds hidden relationships
Improves business decisions
Useful in recommendation systems
Easy to interpret
## Disadvantages
Computationally expensive for large datasets
Generates many unnecessary rules
Requires careful threshold selection

## implementation

##### NOTE :
  for training we are not using the scikitlearn (sklearn ) beacause it does not supports some clsses and functionsn of apriori algorithm

  so we are using apyori module

### importing libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

### Data preprocessing

In [2]:
dataset = pd.read_csv('Market_Basket_Optimisation.csv',header=None) # our dataset does not has any header 


# apriori model expects the dataset in some other format not in pandas , it acepts in list of transaction , so we use for loop to iterate all tge transaction of the dtset 
transactions =[] # creating a empty list 
for i in range (0, 7501):#row
    transactions.append([str(dataset.values[i,j])for j in range (0,20)])# col
    # dataset.values[i,j]) index of row (i) and index of column (j) , but here we cant access the s=datset directly  so we are implementing '.values'
    # and it is a rule that all the elemnts in list should be string , so we have passed  'str'

### Training the Apriori model on the dataset

In [4]:
from apyori import apriori
rules_ap_obj = apriori(transactions=transactions,min_support=0.003, min_confidence= 0.2,min_lift = 3, min_length = 2, max_length = 2)

### Visualizing the results

### Displaying the first results coming directly from the output of the apriori function

In [ ]:
results = list(rules_ap_obj) # high cahnce of buying is predicted/ said using confidence 
results

[RelationRecord(items=frozenset({'chicken', 'light cream'}), support=0.004532728969470737, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.29059829059829057, lift=4.84395061728395)]),
 RelationRecord(items=frozenset({'mushroom cream sauce', 'escalope'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)]),
 RelationRecord(items=frozenset({'pasta', 'escalope'}), support=0.005865884548726837, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.3728813559322034, lift=4.700811850163794)]),
 RelationRecord(items=frozenset({'fromage blanc', 'honey'}), support=0.003332888948140248, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fromage blanc'}), items_add=frozenset({'honey'}), confidence=0.2450980392156863, lift=5.164270764485569)]),
 RelationRecord(items=frozenset({'ground beef', 'herb & pepper'}), support=0.015997866951073192, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2919938411349285)]),
 RelationRecord(items=frozenset({'ground beef', 'tomato sauce'}), support=0.005332622317024397, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.3773584905660377, lift=3.840659481324083)]),
 RelationRecord(items=frozenset({'olive oil', 'light cream'}), support=0.003199573390214638, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'olive oil'}), confidence=0.20512820512820515, lift=3.1147098515519573)]),
 RelationRecord(items=frozenset({'olive oil', 'whole wheat pasta'}), support=0.007998933475536596, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.2714932126696833, lift=4.122410097642296)]),
 RelationRecord(items=frozenset({'pasta', 'shrimp'}), support=0.005065991201173177, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050847, lift=4.506672147735896)])]

### putting the reults well organised into a Pandas DataFrame

In [9]:
def inspect(results):
    lhs = [tuple(result[2][0][0])[0] for result in results]
    rhs = [tuple(result[2][0][1])[0] for result in results]
    supports = [result[1] for result in results]
    confidence = [result[2][0][2] for result in results]
    lifts = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports , confidence ,lifts))
resultsinDataFrame = pd.DataFrame(inspect(results),columns = ['left hand side', 'right hand side','support','confidence','lift'])

### Displaying the results non-sorted

In [10]:
resultsinDataFrame

         left hand side right hand side   support  confidence      lift
0           light cream         chicken  0.004533    0.290598  4.843951
1  mushroom cream sauce        escalope  0.005733    0.300699  3.790833
2                 pasta        escalope  0.005866    0.372881  4.700812
3         fromage blanc           honey  0.003333    0.245098  5.164271
4         herb & pepper     ground beef  0.015998    0.323450  3.291994
5          tomato sauce     ground beef  0.005333    0.377358  3.840659
6           light cream       olive oil  0.003200    0.205128  3.114710
7     whole wheat pasta       olive oil  0.007999    0.271493  4.122410
8                 pasta          shrimp  0.005066    0.322034  4.506672

### displaying the results sorted by descending lifts

In [11]:
resultsinDataFrame.nlargest(n = 10, columns='lift')

         left hand side right hand side   support  confidence      lift
3         fromage blanc           honey  0.003333    0.245098  5.164271
0           light cream         chicken  0.004533    0.290598  4.843951
2                 pasta        escalope  0.005866    0.372881  4.700812
8                 pasta          shrimp  0.005066    0.322034  4.506672
7     whole wheat pasta       olive oil  0.007999    0.271493  4.122410
5          tomato sauce     ground beef  0.005333    0.377358  3.840659
1  mushroom cream sauce        escalope  0.005733    0.300699  3.790833
4         herb & pepper     ground beef  0.015998    0.323450  3.291994
6           light cream       olive oil  0.003200    0.205128  3.114710